# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de825e73b1f7ac1720b6a6d40dfdeff570fc2ba2d36800ed4acd00d43f3ab94bd01e2bd76fb8ea459c164482f60bf058e4a6211368f3e88698314c0b8e809863

test:
  secret_key_base: 86660046534692a312ef1e4bf74bb88a6bc6e3d4805e03e21cb82f446d6420a6209f3584c1193612a80f85c3bb55e46c9237c0a65ecd46aaca6223862c976baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
